# Generated by Django 2.2.4 on 2019-08-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=200)),
                ('rc', models.ImageField(upload_to='rc_images/')),
                ('insurance', models.ImageField(upload_to='insurance_images/')),
                ('pollution', models.ImageField(upload_to='pollution_images/')),
            ],
        ),
    ]
