# Generated by Django 2.2.4 on 2019-08-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra',
            field=models.TextField(default=' '),
        ),
    ]
